import { ResourceHardnessMap, SageResourcesMints } from "../../Common/GameHandler";
import { PublicKey } from "@solana/web3.js";

export enum Resource {
  arco = "arco",
  biomass = "biomass",
  carbon = "carbon",
  diamond = "diamond",
  hydrogen = "hydrogen",
  iron_ore = "iron_ore",
  copper_ore = "copper_ore",
  lumanite = "lumanite",
  rochinol = "rochinol",
  silica = "silica",
  nitrogen = "nitrogen",
  titanium_ore = "titanium_ore",
  gold_ore = "gold_ore",
  // Additional R4
  fuel = "fuel",
  food = "food",
  ammunitions = "ammunitions",
  toolkit = "toolkit",
  sdu = "sdu",
  // Components
  super_conductor = "super_conductor",
  strange_emitter = "strange_emitter",
  radiation_absorber = "radiation_absorber",
  power_source = "power_source",
  particle_accelerator = "particle_accelerator",
  framework = "framework",
  electromagnet = "electromagnet",
  energy_substrate = "energy_substrate",
  aerogel = "aerogel",
  // Compound Materials
  steel = "steel",
  polymer = "polymer",
  magnet = "magnet",
  iron = "iron",
  hydrocarbon = "hydrocarbon",
  graphene = "graphene",
  electronics = "electronics",
  copper = "copper",
  copper_wire = "copper_wire",
  crystal_lattice = "crystal_lattice",
  council_rfr = "council_rfr",
  field_stabilizer = "field_stabilizer",
  titanium = "titanium",
  gold = "gold",

  // Contracts
  // mud
  mic = "mic", // https://play.staratlas.com/market/mic9ZayXBs7x3T6qgM2VskuaWFC8egCQBkTHcy8BoPM/?r=26a5rhrtgql58pmn
  mcgf = "mcgf", // https://play.staratlas.com/market/mic2AcEbMAjxoYGWaobvTMKzzNraSRVFaDaKEM2YrTD/?r=26a5rhrtgql58pmn
  // oni
  oic = "oic", // https://play.staratlas.com/market/oicT4ECU7nuPBZD2HUg8sb9nG4MDXWaE8vAnzwzXqcg/?r=26a5rhrtgql58pmn
  ocvr = "ocvr", // https://play.staratlas.com/market/oiC26XFt8HR1xzw3Y6WJ9wMTdtY1g9k1mthMqwRAn1X/?r=26a5rhrtgql58pmn
  // ustur
  uic = "uic", // https://play.staratlas.com/market/uicF2zhVoZguiFbr2KWp3kFBYwezs6HZqMzQfLbXw1A/?r=26a5rhrtgql58pmn
  ucor = "ucor", // https://play.staratlas.com/market/uiC2QNxpUxu1VqFefrbN6eDucaW2g9YnB4EZosMQeec/?r=26a5rhrtgql58pmn
  aerogel_contract = "aerogel_contract",
  arco_contract = "arco_contract",
  crystals_contract = "crystals_contract",
  data_contract = "data_contract",
  diamond_contract = "diamond_contract",
  food_contract = "food_contract",
  metals_contract = "metals_contract",
  plastics_contract = "plastics_contract",
  precious_metals_contract = "precious_metals_contract",
  rochinol_contract = "rochinol_contract",
  water_contract = "water_contract",
  // Faction contracts
  mud_infrastructure_contract = "mic",
  mud_infrastructure_contract_gottis_favor = "mcgf",
  oni_infrastructure_contract = "oic",
  oni_infrastructure_contract_vaors_order = "ocvr",
  ustur_infrastructure_contract = "uic",
  ustur_infrastructure_contract_opos_request = "ucor",
}

export const resourceHardness: ResourceHardnessMap = {
  arco: 4,
  biomass: 1,
  carbon: 1,
  diamond: 4,
  hydrogen: 1,
  iron_ore: 2,
  copper_ore: 2,
  lumanite: 2.5,
  rochinol: 4,
  silica: 2,
  nitrogen: 1,
  titanium_ore: 5,
  gold_ore: 1,
};

export const SAGE_RESOURCES_MINTS: SageResourcesMints = {
  // ########## C2 ################
  arco: new PublicKey("EQoKx7fpExDwH452Ffds7SYhcq7rBF5cSKwB4xkkEefa"),
  biomass: new PublicKey("a7dYqXF3ajBW4ZuquMBDBeouTZRuyP44gBAtoWPPjCY"),
  carbon: new PublicKey("Fim62oYfcQrtSVSreTj8jEDuiaQT1LzK33tiN7PJQtMq"),
  copper_ore: new PublicKey("FMLx4SKtpf2psnubEXSQyfXPYjBdJb8z8Z3DUhZq3GNg"),
  diamond: new PublicKey("GszHsMNqF7fe46ZSZfkHb2pLSKmXyptEhjUcH91ASQy5"),
  gold: new PublicKey("6ffsSRGwrrY7LDjujKL2JEWohu6hbga6nShxn6Ehv84X"),
  gold_ore: new PublicKey("7Wt6jgztwBh7RV2iXadWQyZPiumMVAL9vWodbjRSHtjc"),
  hydrogen: new PublicKey("7JLYv8FYC3PS5uWHm1fe7H9zxobrz86TYAtqxpcMCnWY"),
  iron_ore: new PublicKey("2uQE6ZtF6vZbZhjYuCSdWKWNYFPS7Dxtbk8LqQgFHLBA"),
  lumanite: new PublicKey("9NHb9kvzd5m5KYmAtAGqUvkxBkuM1hXffiq6gjVV7E8o"),
  nitrogen: new PublicKey("HwJXKQeCwqJBjEEcHAFyBMp27JTGoX4EudUSQc7S8Thg"),
  rochinol: new PublicKey("5DqKLaF2Qf6XLtvYUcZjFKwjvN3BWWMvJGWdX7Y6uysu"),
  silica: new PublicKey("GF62USERj2UZ1wCt2K8qHs2dGQcVgXsy6ggTQfMA1WTK"),
  titanium_ore: new PublicKey("6MDYL1NdU54XYsMnCWUW8sd3BS6zfs3jdDvYHELYM55c"),
  survey_data_unit: new PublicKey("BMzEZ5Fg9kxsWo318xSabghsPJCSc4B1Th7oSvdpU94c"),
  sdu: new PublicKey("BMzEZ5Fg9kxsWo318xSabghsPJCSc4B1Th7oSvdpU94c"),

  // R4
  ammunitions: new PublicKey("3YMSL96H5oKbUywneD7LLH1ehemRHPRS5NmmXdkHuuN8"),
  ammo: new PublicKey("3YMSL96H5oKbUywneD7LLH1ehemRHPRS5NmmXdkHuuN8"),
  ammunition: new PublicKey("3YMSL96H5oKbUywneD7LLH1ehemRHPRS5NmmXdkHuuN8"),

  food: new PublicKey("FkuNf3SdTGE2bD2EENL8XA9dtrm4LuvvubkLhMPaY79K"),
  fuel: new PublicKey("C7NBrwq9tpCwprfYVEGg8YXUMhfFaNqwrkEQrzF9sMPL"),
  toolkit: new PublicKey("J6g3oGh83ZHGkiw4yxpWpLbAde3t5hRy7Q65jCu4mE29"),

  // Compound Materials
  aerogel: new PublicKey("8xqThQtixn2wujdc9bhhgkDquFsCbCpBHZBLjqTd8e6B"),
  copper: new PublicKey("2B1B1oqvVYXggDxTXWSL8zQiAZ1ApcE3SBznKEN7Cr9x"),
  copper_wire: new PublicKey("Le91HfAtL6rSCWUiF9cRaY1zY7nfwe67gAgNJRqqn58"),
  crystal_lattice: new PublicKey("b7GxjPFTUrJUeeYjybS4FSiTEYeLGw3V2SYRxbdHsAY"),
  electronics: new PublicKey("3pzjUgHciHjZBYkqbMqHYavGJRYZg9982DQ6VKSC31mL"),
  field_stabilizer: new PublicKey("CxmFQBt5C3tp9P7truLbjkGhsJJW8gxNTbM6ntxnifNu"),
  graphene: new PublicKey("AFZCBuj98dXwXWUShhVKBKaTe54jAD2duDc64N59o9mz"),
  hydrocarbon: new PublicKey("9DAtKFzTEMzAo28oXdWFSkrRJXc9DGE5WChnLTK35dNf"),
  iron: new PublicKey("GkNuu3BEgB6WST48hUaP1RULv8zWEMDqjaw2y8xVK4tm"),
  magnet: new PublicKey("kUgarC6sv28KxZysZ4qPguafscJpKJhHvutk7H7F9yA"),
  polymer: new PublicKey("DXD8peBJsSbHqx7hYoBg8qqWL8YJphHHDGcuMu7yVjAf"),
  steel: new PublicKey("9JUUfjZnKaKZmoiE35RreU21htJyTjarnmcfaiC5Fntp"),
  titanium: new PublicKey("CqoeUqR3FdjNwm6GM15oU6aWAFS8oNmwdvwhycpEjyYc"),

  // Components
  electromagnet: new PublicKey("BcJS6vrPHk6u5dtE1asDuuFvho19677HSggvN8Myvdke"),
  energy_substrate: new PublicKey("HpSMKY2pYQU5DrYPYmm4MSNHXYNMq2hix6FD72x5udko"),
  framework: new PublicKey("5D7VWkin7YtKTDwYg7Xue9CkKKZ8bu8qE4KunjP2zxTd"),
  particle_accelerator: new PublicKey("65r9cVm1YkNfoaqMERWtrJJ9hu48nkJHYxbhU4BLN8uc"),
  power_source: new PublicKey("GqjvJ3dtuLYN3HXUX6rMKNv3wgnTLvSLcCbb3EZBiumM"),
  radiation_absorber: new PublicKey("8f8m9Q12BWYNkFiV6rwqxxukXEWHeYeYRpn2bx3hBP7W"),
  strange_emitter: new PublicKey("BJDoskqhL4NPnMKT8FasJxnKnZc9QXngL1ssZag4mFR5"),
  super_conductor: new PublicKey("4hDgwDdzyHQSft7koJnFnupxZUtjQVUyxeTZM9YHNxvv"),

  // ########## C1 ################
  // ammunitions: new PublicKey("5rX9cdkzsafEKK8SXfV4ZhkWa8YZD36EEUgh6yVUGibm"),
  // food: new PublicKey("2zVDqh6kUKqwjqP5wT52PQTf4ymHmJg3GXa5p8of9W4w"),
  // fuel: new PublicKey("3dHCHeNvUem61tbd44bSTbtMozGR3VYcZwNM4KTDmzu2"),
  // toolkit: new PublicKey("8i34JNdrXax7ACYFHZV26cUmR7usWcw2NL2j5epVFdA1"),
  // aerogel: new PublicKey("9roiK8MTRtKHxzCEwUk8JpKY5YfA7VK3ps4pFzp6X3Rt"),
  // copper: new PublicKey("2rQvGLhHGiZ2sCCXJWbcz2d89W5rfgeSBx3HCDBuKYdg"),
  // copper_wire: new PublicKey("95xFarGsCRxhMyNeTm8pZ5pZqVJM96Ty7qiARQJPBnmH"),
  // crystal_lattice: new PublicKey("5TmTxfa5fAmK8Lvx3HdBSQCn7yMC6gPuP8TF9MGaSbTQ"),
  // electronics: new PublicKey("GXPuQyorkdDkmqbyANw1XHCw5G49bDp3GLdvbydQy3Fs"),
  // field_stabilizer: new PublicKey("2kt4fPUvf876URX1VrgUwpHRTx1kSNh2RcaffkPEqE6W"),
  // graphene: new PublicKey("6Qm11oxZbsSDn8pqBFypCeJoYJPmXfpwG6Kv8i7nMj6c"),
  // hydrocarbon: new PublicKey("7Bdr41guasV8AKkKBy142GQF217b7WG4TLiBXzDn9MfT"),
  // iron: new PublicKey("2F8zjXvNytUKwvYXmuQ3UEKoPhANw9fPwcV7AHE1Jm19"),
  // magnet: new PublicKey("95uP9rFbawL1fcn1SndxyPw7rheZL61pUTaxr5eYzdkG"),
  // polymer: new PublicKey("2B4kowewN9WqhLaKavwXaT3mVxkfU9BvhCWKoaXkqMDC"),
  // steel: new PublicKey("2zwYUdwiNXtEyRCDad1Xhctj2TWtAshG8cbhAk7wKKvM"),
  // titanium: new PublicKey("8iETtUaxPk5vA5gD4NupTBmqknBokBSRPJvn9Y7xdKbf"),
  // arco: new PublicKey("Gk29WEQvaBKnyeuULgD8hMkSahPPU4eAy1GCyvzhNsQe"),
  // biomass: new PublicKey("AMVj9EZBpN3KRTLL4zNMQUbcYTq2KYiVwoiPGoCd12bo"),
  // carbon: new PublicKey("Ep9kZiZscFToTBBAL4oaHpwMhWwdpkoHTwJwpFaPAWby"),
  // copper_ore: new PublicKey("2BHYjr1SrEm7Nrj1NtpLHpKMmBzGXSRxXFQLUk3tfGGX"),
  // diamond: new PublicKey("HqYxRSnfCYbdbd5ZdH2iJnNeyhF1ho3f3b7SA6Xt85UM"),
  // gold: new PublicKey("PU3igJsrb61ibE4RWq6d7yNWH6tPCc5BK8HUD9pcvxD"),
  // gold_ore: new PublicKey("5mSnvxHQa2ankDqC7e2TNE1QrSJJSsQXdFv5iSE2VrNo"),
  // hydrogen: new PublicKey("HXBCEQgLSurH1H5vCGuSsTwk9e82a4bjNnHtgy1xfq7C"),
  // iron_ore: new PublicKey("5DSMYZxHhMf3S95jkGXMJvA3PrMg32Lvfbk5hnULnvXu"),
  // lumanite: new PublicKey("41cgdBemSqqAvjELmi3CEnYFdnHiZp3e45PXSchrh2C3"),
  // nitrogen: new PublicKey("3BZXdxcTMPpGWNGTFhKknDYNXJ1q4cwqLkNHFUcHpx7W"),
  // rochinol: new PublicKey("9RfZ3frZhyL3DiHjCYwEWzXadNPuZnAMkVpno1YNwUX2"),
  // silica: new PublicKey("3buSQmcp2xttmm6HqXvXXn8nN8h6TXnbGcDSsWhDySxh"),
  // titanium_ore: new PublicKey("42xFmz3wdcNF58HcAwQ2DwQJkFrXuujX79kkhrkybdqi"),
  // combat_permit: new PublicKey("8tkv5qEWy9Lirfc13HhECwV8V3why5w73uLDMX73eacU"),
  // merchant_permit: new PublicKey("CCj2VPuHBjKieiNwdSr7VowR8WyYhgqn53cn81YXoLkZ"),
  // mining_permit: new PublicKey("CFU1Zf8pLLrDLkiERr8rxGciRnbj8mc3RHDLfp37GQyc"),
  // scanning_permit: new PublicKey("6kRH3zRMtrNz4BocZr54i8zwpEiAnafaBVRA9yZHPJ2A"),
  // electromagnet: new PublicKey("ErkN7SmyHQFxbWPoiXCpEenjsRr462acQFK7e811ecP"),
  // energy_substrate: new PublicKey("BZ4a27rMHYCzEbUVzqKkGri7twBhn9NWaooEEBN9JVC6"),
  // framework: new PublicKey("4uYib4Fr5C9HPgvrkkZPk4re5eZJsVaMV6Q1U4Skzd8T"),
  // particle_accelerator: new PublicKey("Hh3mC1EESH5KXiDBh6or1hD2kHyKgahHsCB8qqKib3vs"),
  // power_source: new PublicKey("9CQNXJQGQKLw7EAiZooZuEzm5zJ7CkP7CmefAGDYDDGv"),
  // radiation_absorber: new PublicKey("HFvjuUp4zzX9qdz6Vkh6m6xnr61LoArsMkKvyTe8L9G8"),
  // strange_emitter: new PublicKey("CGPbqKZzwadESRK5hHShCSZS5fYkNxupZ38qvmfhXsau"),
  // super_conductor: new PublicKey("J8pSCYywe9hTeMvbo8Egxqtd36n72T7g1s787UcEhMsi"),
  // survey_data_unit: new PublicKey("45uKMS7U99QeZySMMhqxhXafjXxJUiQxUKTRijqt92jo"),
  // sdu: new PublicKey("45uKMS7U99QeZySMMhqxhXafjXxJUiQxUKTRijqt92jo"),
  //  ! HOLOSIM CONTRACTS
  //  * Not exists in chapter 2
  aerogel_contract: new PublicKey("7tUVG4pRijrvYi8wEYSZuxUtbPHRzsPELiVpBiVrXmJ8"),
  arco_contract: new PublicKey("EAfiU1BNSc4rdrAdbnpW22RdstKZB4Wh6W5YnscktyYh"),
  crystals_contract: new PublicKey("2EMbKbg2kBMiHatxdq1zkCpXwnR7P39iWNXTci4HRfYH"),
  data_contract: new PublicKey("9QNrmr71XFMcginycLzQKP288kSmu823d1GcLgNF9oVE"),
  diamond_contract: new PublicKey("hy2e8Gcmrc4Xj6Ku3raiKTftE78FXrEhHbmwofu8h8n"),
  food_contract: new PublicKey("939zMyjoa4mrPu3jtJdUyFS9GgKXiWaN4MMfebUYcCEg"),
  mud_infrastructure_contract: new PublicKey("G64FE8bWQjTuvri8sqeVdhSGFcc3tVsszUEhUG5S1jsQ"),
  mud_infrastructure_contract_gottis_favor: new PublicKey("fRSVTdriFpd4X2VRdwhyBvhWUT3hcimD85Qh6jinZL8"),
  metals_contract: new PublicKey("HC35Gi58ewt2W6q1DU8bVYfytUzPxaEvVoA6hGkEqFDy"),
  oni_infrastructure_contract: new PublicKey("ELGWaFMwU2iRjvZiTbAL8yV3wYj3iCpd4o8KyMkWjMDh"),
  oni_infrastructure_contract_vaors_order: new PublicKey("5JVUxVd1R2HUvtboTSaSnMKQcBGmrkdSduThKcwqbWdq"),
  plastics_contract: new PublicKey("BaCG5ebvNQKkYEqTwCfurYYcfWCehaJ8tF7cLyZJ7aUp"),
  precious_metals_contract: new PublicKey("Fp7GNqpCfQxbetfrPM1Nnihhkav2CRBdWcA7YU9x1qxZ"),
  rochinol_contract: new PublicKey("ErQHTdktL1LSR7wNKnGHtL6tW9qBbsEwQ79WaQNcob1m"),
  ustur_infrastructure_contract: new PublicKey("HcXUmzicgJAUyhMJjKQggByhjiZ6U7hDW2xzvCqREVZx"),
  ustur_infrastructure_contract_opos_request: new PublicKey("6AjUkXBs2yZUotraTDRAAM8fkP3tUmHKhAcVYxKCv6rQ"),
  water_contract: new PublicKey("7evaiM5YYwBqBsJRrXE4CUqjsKEjAE88P4xcf7tF8Tcj"),
};
