import { StarbaseMap } from "../../Common/GameHandler";
import { Coordinates } from "../../Model/Coordinates";
import { Resource } from "./Resource";

export const starbaseMapInstance: StarbaseMap = {
  /*
   * MUD
   */
  mud1: {
    name: "MUD-1",
    fraction: "MUD",
    starbasePublicKey: "8Hr93jyQUiZfa4CQQiJ48CAZbotcUYWPMBVzzYb49nss",
    location: new Coordinates(0, -39),
    resources: [Resource.hydrogen],
    richness: [1],
  },
  mud2: {
    name: "MUD-2",
    fraction: "MUD",
    starbasePublicKey: "7zomNZp3Z1sjAhNqrvPoWcmshXFHGgUu7FLJrqQtUNkG",
    location: new Coordinates(2, -34),
    resources: [Resource.iron_ore],
    richness: [1],
  },
  mud3: {
    name: "MUD-3",
    fraction: "MUD",
    starbasePublicKey: "6pkHA9CPF6xm49TLVN9iJuHn5QF7V2kMvpBFyJBWsHrn",
    location: new Coordinates(10, -41),
    resources: [Resource.carbon],
    richness: [1],
  },
  mud4: {
    name: "MUD-4",
    fraction: "MUD",
    starbasePublicKey: "NxvHJR6dQz8KB7WRdwQnHVJphqQ7FEat7VW3rsg5qiY",
    location: new Coordinates(-2, -44),
    resources: [Resource.biomass],
    richness: [1],
  },
  mud5: {
    name: "MUD-5",
    fraction: "MUD",
    starbasePublicKey: "HVh1yZFxpSXwtrguy8CNHtBQc91uC51xCqYuTAVj64N7",
    location: new Coordinates(-10, -37),
    resources: [Resource.copper_ore],
    richness: [1],
  },
  mrz1: {
    name: "MRZ-1",
    fraction: "MUD",
    starbasePublicKey: "98E4PDEwAYFCNcdbt5EL7JYMj5Rqpd4BkMRsDuYBaytF",
    location: new Coordinates(-15, -33),
    resources: [Resource.iron_ore, Resource.nitrogen],
    richness: [1.5, 1.5],
  },
  mrz2: {
    name: "MRZ-2",
    fraction: "MUD",
    starbasePublicKey: "13wRULPgbZrL9H6W3ov5uvRza3PVtDxegfNzSPCymuEu",
    location: new Coordinates(12, -31),
    resources: [Resource.silica, Resource.lumanite],
    richness: [1, 1],
  },
  mrz3: {
    name: "MRZ-3",
    fraction: "MUD",
    starbasePublicKey: "5wvPB4CWed1abXqYH3QCRpt8mZQjrD1wqRcxXGtY1psx",
    location: new Coordinates(-22, -25),
    resources: [Resource.carbon, Resource.copper_ore],
    richness: [1.5, 1.5],
  },
  mrz4: {
    name: "MRZ-4",
    fraction: "MUD",
    starbasePublicKey: "Bo2YeykUnWBsvvhXuM1D59jLxMEigKmK4DFiyyMTbsnp",
    location: new Coordinates(-8, -24),
    resources: [Resource.hydrogen],
    richness: [1.5],
  },
  mrz5: {
    name: "MRZ-5",
    fraction: "MUD",
    starbasePublicKey: "9tzsPX6uSUxd1coA2yMYDrmVfQQGJZdZG1qDeghxeSqu",
    location: new Coordinates(2, -23),
    resources: [Resource.hydrogen, Resource.carbon],
    richness: [1.5, 1.5],
  },
  mrz6: {
    name: "MRZ-6",
    fraction: "MUD",
    starbasePublicKey: "6aeaH8q7unhosrg3rn3eqi3pUz1DxDyU2aQvGPF2s6dg",
    location: new Coordinates(11, -16),
    resources: [Resource.hydrogen, Resource.copper_ore],
    richness: [2, 2],
  },
  mrz7: {
    name: "MRZ-7",
    fraction: "MUD",
    starbasePublicKey: "3nr31TrYC7xt6qecNkWL5WwQTV2w1gDWmb84V8E5cGa1",
    location: new Coordinates(21, -26),
    resources: [Resource.biomass, Resource.iron_ore],
    richness: [1.5, 1.5],
  },
  mrz8: {
    name: "MRZ-8",
    fraction: "MUD",
    starbasePublicKey: "9jXHpNaF5uXypLdFkUjFqTpDXkhjYizkxkfXFnFzQZjF",
    location: new Coordinates(-30, -16),
    resources: [Resource.titanium_ore],
    richness: [2],
  },
  mrz9: {
    name: "MRZ-9",
    fraction: "MUD",
    starbasePublicKey: "HwSUG1sUzvk3HTyYDQk4Fx9Lk7NBGjSYKVMgUxZozp6B",
    location: new Coordinates(-14, -16),
    resources: [Resource.biomass, Resource.carbon],
    richness: [1.5, 1.5],
  },
  mrz10: {
    name: "MRZ-10",
    fraction: "MUD",
    starbasePublicKey: "mAfGxchko6ZU8bRpVHQHXjfYEGBsPwmzGWxUuo4csCa",
    location: new Coordinates(23, -12),
    resources: [Resource.lumanite],
    richness: [1.5],
  },
  mrz11: {
    name: "MRZ-11",
    fraction: "MUD",
    starbasePublicKey: "6nuTqwN5pPaF7KrPg6A82HigwwzuXPA4hRomfvmQyY8t",
    location: new Coordinates(31, -19),
    resources: [Resource.carbon],
    richness: [2],
  },
  mrz12: {
    name: "MRZ-12",
    fraction: "MUD",
    starbasePublicKey: "4a1ZvTYdSxo688PNqVwWHzmnoLkm2Hw246DGwxRw8PTE",
    location: new Coordinates(-16, 0),
    resources: [Resource.diamond],
    richness: [1],
  },
  mudPhantom: {
    name: "MUD-PHANTOM",
    fraction: "MUD",
    starbasePublicKey: "8e84MFqx2d6bnDEL81My86uNDaNGPkCLP8RF7XkLhi1D",
    location: new Coordinates(0, -24),
    resources: [],
    richness: [],
    craftingFacility: "AJ4KsL2YWcBuTpidtLujhL2ET1kCZWVdFVPqUd9uQUte",
    upgradeFacility: "ExPsrh8hu5UKCrJofzTE733ptSnmfwsQ9Fef81XwRBzP",
  },

  /**
   * Oni Starbases
   */
  oni1: {
    name: "ONI-1",
    fraction: "ONI",
    starbasePublicKey: "5LVVJEAYEQPMoKp45r7GfNcnNDro1oFDgnLo7XHha3Xp",
    location: new Coordinates(-40, 30),
    resources: [Resource.hydrogen],
    richness: [1],
  },
  oni2: {
    name: "ONI-2",
    fraction: "ONI",
    starbasePublicKey: "C4gwAfZX2itwyLQGjHQmM5ZEEbvJ73VdMYRARMggHTfX",
    location: new Coordinates(-42, 35),
    resources: [Resource.biomass],
    richness: [1],
  },
  oni3: {
    name: "ONI-3",
    fraction: "ONI",
    starbasePublicKey: "EtepVfgCfyKAJg4B9QYG5BeSW3oRzMsKPHz7Ld1Hsa5V",
    location: new Coordinates(-30, 30),
    resources: [Resource.carbon],
    richness: [1],
  },
  oni4: {
    name: "ONI-4",
    fraction: "ONI",
    starbasePublicKey: "GE7Ud3sT16M1NC7xW9YYzSB9dnPWvExgWAZYzxshwgim",
    location: new Coordinates(-38, 25),
    resources: [Resource.iron_ore],
    richness: [1],
  },
  oni5: {
    name: "ONI-5",
    fraction: "ONI",
    starbasePublicKey: "EcL56x62fJ4dWiDJSRwSmhgWjTEz73JKSwXybPDh35ME",
    location: new Coordinates(-47, 30),
    resources: [Resource.copper_ore],
    richness: [1],
  },

  mrz13: {
    name: "MRZ-13",
    fraction: "ONI",
    starbasePublicKey: "HnZX2YXwK8KZJVjAECprALtvZWhKNg9HDSzDikiQwN1M",
    location: new Coordinates(-36, -7),
    resources: [Resource.carbon],
    richness: [2],
  },
  mrz14: {
    name: "MRZ-14",
    fraction: "ONI",
    starbasePublicKey: "5yWdAS3mLbtVC9XZyRkntEn2n5ESkTQHdxccR7rYU9hT",
    location: new Coordinates(-23, 4),
    resources: [Resource.lumanite],
    richness: [1.5],
  },
  mrz18: {
    name: "MRZ-18",
    fraction: "ONI",
    starbasePublicKey: "5Wnow7ZgiAoEiGr78fSuxuTxUaSBLktKCG8hH2uNauYY",
    location: new Coordinates(-40, -3),
    resources: [Resource.biomass, Resource.carbon],
    richness: [1.5, 1.5],
  },
  mrz19: {
    name: "MRZ-19",
    fraction: "ONI",
    starbasePublicKey: "HaTpXV4UbfzVNdRVvAfyka76h7CK5CeB9JZuRWataFCg",
    location: new Coordinates(-35, 12),
    resources: [Resource.carbon, Resource.copper_ore],
    richness: [1.5, 1.5],
  },
  mrz20: {
    name: "MRZ-20",
    fraction: "ONI",
    starbasePublicKey: "HctDXX6qb77pcm8CAaWQLd2dTFPAF9wqJ6NNgmdAerFX",
    location: new Coordinates(-25, 15),
    resources: [Resource.hydrogen, Resource.carbon],
    richness: [1.5],
  },
  mrz24: {
    name: "MRZ-24",
    fraction: "ONI",
    starbasePublicKey: "9cgP7ac5PVvm7boZbGrVVraLo5DxWp2YuS11gAhDAcLH",
    location: new Coordinates(-45, 15),
    resources: [Resource.iron_ore, Resource.nitrogen],
    richness: [1.5, 1.5],
  },
  mrz25: {
    name: "MRZ-25",
    fraction: "ONI",
    starbasePublicKey: "8VMr5W3EPyyUqprC9W7Lwjr2mMEWxFGGx7TtoSJuQueq",
    location: new Coordinates(-18, 23),
    resources: [Resource.hydrogen],
    richness: [2],
  },
  mrz26: {
    name: "MRZ-26",
    fraction: "ONI",
    starbasePublicKey: "Ce7NahqL9T6DSKcM3VmMzSvGSpYCxzk4PxuEJsHfFvFN",
    location: new Coordinates(-9, 24),
    resources: [Resource.copper_ore, Resource.hydrogen],
    richness: [1.5, 1.5],
  },
  mrz29: {
    name: "MRZ-29",
    fraction: "ONI",
    starbasePublicKey: "8EbNGvTnncC4Qo3wkXNAdZxvx211WfbgpDsGbFNwjBJP",
    location: new Coordinates(-22, 32),
    resources: [Resource.silica, Resource.lumanite],
    richness: [1, 1],
  },

  mrz30: {
    name: "MRZ-30",
    fraction: "ONI",
    starbasePublicKey: "9DwqdnpuRU2AnTDYKT8oqb8Y3AS8i1sC6ywjkJV5C7mV", // ! WRONG ADDRESS
    location: new Coordinates(-19, 40),
    resources: [Resource.titanium_ore],
    richness: [2],
  },

  mrz31: {
    name: "MRZ-31",
    fraction: "ONI",
    starbasePublicKey: "9DwqdnpuRU2AnTDYKT8oqb8Y3AS8i1sC6ywjkJV5C7mV",
    location: new Coordinates(-8, 35),
    resources: [Resource.titanium_ore],
    richness: [2],
  },
  mrz36: {
    name: "MRZ-36",
    fraction: "ONI",
    starbasePublicKey: "3BAQgLWLZkqczEVA1LKvaAc48mgC18JCVepWJG8wYgTJ",
    location: new Coordinates(0, 16),
    resources: [Resource.rochinol],
    richness: [1],
  },

  oniPhantom: {
    name: "ONI-PHANTOM",
    fraction: "ONI",
    starbasePublicKey: "6jwC8E4zVySLaZsiTo1A7REGAp2tKwPJLv9cc6WCFNLC",
    location: new Coordinates(-28, 21),
    resources: [],
    richness: [],
    craftingFacility: "HBK2GJGukZy6DVheuNrZjo7LbUQnAhhvGXfyCL94kGpw",
    upgradeFacility: "DSPPke8z2CB1RMrBHPf8B2ydVkV3KDX44MbTj5nGoiVB",
  },
  /**
   * Ustur Starbases
   */
  ust1: {
    name: "UST-1",
    fraction: "UST",
    starbasePublicKey: "94LdKdSHuG3Na6H1YhkgJsq1caYVxUNeBRm7rLB6hd8k",
    location: new Coordinates(40, 30),
    resources: [Resource.hydrogen],
    richness: [1],
  },
  ust2: {
    name: "UST-2",
    fraction: "UST",
    starbasePublicKey: "D8KcjKhELZPwhJcamfqnpAnUe5LcTXV3sFwuQeaFK8Es",
    location: new Coordinates(42, 35),
    resources: [Resource.biomass],
    richness: [1],
  },
  ust3: {
    name: "UST-3",
    fraction: "UST",
    starbasePublicKey: "2jijEHvJasRvTJLV9uXyWY9MxaqHQgfU42JQTyStBTe7",
    location: new Coordinates(48, 32),
    resources: [Resource.carbon],
    richness: [1],
  },
  ust4: {
    name: "UST-4",
    fraction: "UST",
    starbasePublicKey: "ATEHz1f1HzDpEeuSaxYzmSrARqg3txpoQCwHB2kjA8kY",
    location: new Coordinates(38, 25),
    resources: [Resource.iron_ore],
    richness: [1],
  },
  ust5: {
    name: "UST-5",
    fraction: "UST",
    starbasePublicKey: "G66MYx8sREyEvFoGPHNHN5bXpTovBETaN2A2dSWfQit3",
    location: new Coordinates(30, 28),
    resources: [Resource.copper_ore],
    richness: [1],
  },
  mrz15: {
    name: "MRZ-15",
    fraction: "UST",
    starbasePublicKey: "2LRnxdw5vBiF9rQbyyNYoPhChLHmg2rKNtRXxxfzfa56",
    location: new Coordinates(22, 5),
    resources: [Resource.copper_ore, Resource.hydrogen],
    richness: [1.5],
  },
  mrz16: {
    name: "MRZ-16",
    fraction: "UST",
    starbasePublicKey: "7T6Z2xijackDVWhazBj3iA4q1gu3smxgtyh4ujk4DzAY",
    location: new Coordinates(39, -1),
    resources: [Resource.titanium_ore],
    richness: [2],
  },
  mrz17: {
    name: "MRZ-17",
    fraction: "UST",
    starbasePublicKey: "4Ryjdp4fXZRNKhZfytSpmKCnNMc6ZAtP7kcjQzS2tzJo",
    location: new Coordinates(16, -5),
    resources: [Resource.arco],
    richness: [1],
  },
  mrz21: {
    name: "MRZ-21",
    fraction: "UST",
    starbasePublicKey: "6W2P5xbxUa6pKsNvErAXjc1sn6HHpUguYikoAAFxdiW1",
    location: new Coordinates(25, 14),
    resources: [Resource.hydrogen],
    richness: [2],
  },
  mrz22: {
    name: "MRZ-22",
    fraction: "UST",
    starbasePublicKey: "2ugE9KwRKjSyMMT5jRgDvcmoHUZPuWG5KsphFeD9zrUR",
    location: new Coordinates(35, 16),
    resources: [Resource.copper_ore, Resource.carbon],
    richness: [1.5],
  },
  mrz23: {
    name: "MRZ-23",
    fraction: "UST",
    starbasePublicKey: "Hb8iAmumeNRccHXGLCGMEz2PMXu1yTxsfB5LSD7yhAqi",
    location: new Coordinates(44, 10),
    resources: [Resource.iron_ore, Resource.biomass],
    richness: [1.5],
  },
  mrz27: {
    name: "MRZ-27",
    fraction: "UST",
    starbasePublicKey: "9w2Ytk1KSm3NL6qZNCNMkGLDyyZrpHSyhHDPBNBAUwJU",
    location: new Coordinates(2, 26),
    resources: [Resource.lumanite],
    richness: [1.5],
  },
  mrz28: {
    name: "MRZ-28",
    fraction: "UST",
    starbasePublicKey: "DxVDHLQ43zUEXkh9BRqWgeh7agY854bztNWCarMbmFW6",
    location: new Coordinates(17, 21),
    resources: [Resource.hydrogen, Resource.carbon],
    richness: [1.5],
  },
  mrz32: {
    name: "MRZ-32",
    fraction: "UST",
    starbasePublicKey: "FCX2CgE9ptWZM2WuZHhhmJxnFjkPNm1tLToTxx1Ljzaj",
    location: new Coordinates(5, 44),
    resources: [Resource.carbon],
    richness: [2],
  },
  mrz33: {
    name: "MRZ-33",
    fraction: "UST",
    starbasePublicKey: "CmPSrYZznzuzMU17Xo6r79vWmpASVZLQgLM8zGmfBqDa",
    location: new Coordinates(13, 37),
    resources: [Resource.biomass, Resource.carbon],
    richness: [1.5],
  },
  mrz34: {
    name: "MRZ-34",
    fraction: "UST",
    starbasePublicKey: "6xSmiUAY646H46BAoXPQESqho5YPbjvX4RMFM7PKwdaz",
    location: new Coordinates(22, 31),
    resources: [Resource.lumanite, Resource.silica],
    richness: [1],
  },
  mrz35: {
    name: "MRZ-35",
    fraction: "UST",
    starbasePublicKey: "Cy3mxgxshchCUgM7JuQFU2Q18wAAV6QZQZ6mxypxiizL",
    location: new Coordinates(49, 20),
    resources: [Resource.nitrogen, Resource.iron_ore],
    richness: [1.5],
  },
  //! ustur-phantom
  uPhantom: {
    name: "USTUR-PHANTOM",
    fraction: "UST",
    starbasePublicKey: "CfNRa2nEo2hERZJhztyBmtUmu1VARRErjPmjeAFwpst6",
    location: new Coordinates(28, 21),
    resources: [],
    richness: [],

    craftingFacility: "6x9uy1QvsRtQsKVv9eerktzHetR1etEJd8dgUfVDVCkC",
    upgradeFacility: "39f8BTwcpd8W7yY8ogBhAV7yG94w96L49WZVuv4Uf6bN",
  },
};
